@extends('layout.front')

@section('content')

    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <div class="card border-0 shadow-sm">
                    <div class="card-header border-0 bg-primary py-1"></div>
                    <div class="card-body">
                        <div class="header mt-3 mb-5 d-flex justify-content-center">
                            <h2 class="title-under-decoration">Syarat Penggunaan</h2>
                        </div>
                        <div class="content">
                            
                            <p class="fw-500">Penerimaan Ketentuan Penggunaan</p>
                            <p class="fs-sm text-gray">
                                Ketentuan Penggunaan Komiktoon ini berlaku untuk akses dan penggunaan Anda atas Aplikasi Komiktoon, Situs Web Komiktoon, dan akses ke dan penggunaan halaman web, platform, layanan, atau konten di dalamnya atau disediakan olehnya (secara kolektif, "Layanan") yang disediakan oleh Komiktoon. (termasuk afiliasinya, selanjutnya bersama-sama disebut sebagai “Komiktoon”, “kita”, atau “kami”).

                                <br>
                                <br>

                                Dengan menggunakan Layanan, masuk ke Layanan, menerbitkan Posting Pengguna, dan/atau mengklik tombol pada Layanan yang menunjukkan persetujuan Anda, Anda dengan ini menyetujui (1) <span class="text-primary">Ketentuan Penggunaan Komiktoon</span> ini, dan (2) <span class="text-primary">Kebijakan Komunitas kami dan Pedoman Pengunggahan</span>, yang semuanya digabungkan di sini sebagai referensi (secara bersama-sama disebut "Perjanjian"), dan Anda mengakui bahwa Anda telah membaca dan memahami <a href="/privacy-policy" class="text-decoration-none text-primary">Kebijakan Privasi</a> kami. Perjanjian tersebut merupakan keseluruhan perjanjian oleh dan antara Komiktoon dan Anda. Jika Anda tidak ingin menyetujui Perjanjian ini, Anda tidak boleh mengakses atau menggunakan Layanan.
                                
                                <br>
                                <br>

                                Jika Anda menggunakan Layanan atas nama orang atau entitas lain, Anda menyatakan bahwa Anda memiliki wewenang untuk mengikat orang atau entitas tersebut pada Perjanjian, dan kata "Anda" atau "milik Anda" dalam Perjanjian mencakup orang atau entitas lain tersebut.
                                
                                <br>
                                <br>

                                Selain itu, saat menggunakan Layanan, Anda harus tunduk pada pedoman atau peraturan yang diposting yang berlaku untuk layanan, fitur, atau penawaran tersebut yang mungkin diposting dari waktu ke waktu. Semua pedoman atau aturan tersebut dengan ini dimasukkan sebagai referensi ke dalam Perjanjian.
                            </p>


                            <p class="fw-500">Perubahan Ketentuan Penggunaan</p>
                            <p class="fs-sm text-gray">Komiktoon dapat mengubah Perjanjian dari waktu ke waktu dengan menerbitkan versi yang diubah di Situs Web Komiktoon dan/atau Aplikasi Komiktoon. Kami akan berusaha memberi Anda pemberitahuan tentang setiap perubahan pada Perjanjian yang secara material memengaruhi hak Anda dengan menginformasikan kepada Anda melalui email, menawarkan pemberitahuan di dalam Situs Web Komiktoon atau Aplikasi Komiktoon, atau dengan memperbarui tanggal di bagian atas Perjanjian. Anda juga harus secara berkala meninjau versi Perjanjian terbaru di Situs Komiktoon dan/atau Aplikasi Komiktoon. Semua modifikasi Perjanjian yang kami posting di Layanan akan berlaku segera setelah posting, dan penggunaan Layanan yang berkelanjutan setelah kami memposting perubahan pada Perjanjian akan mengonfirmasi penerimaan Anda atas perubahan tersebut. Jika Anda tidak menyetujui Perjanjian yang diubah, Anda harus berhenti menggunakan Layanan.
                            </p>

                            <p class="fw-500">Definisi Sebagai Perjanjian :</p>
                            <ol type="A" class="text-gray fs-sm">
                                <li class="mb-2"><b>“Profil Kreator”</b> mengacu pada Layanan yang memungkinkan Anda untuk menyesuaikan halaman profil pengguna Anda dan membuat sebagian atau seluruhnya publik untuk pengguna Layanan lainnya untuk Masukan dan interaksi.</li>
                                <li class="mb-2"><b>"Konten Digital"</b> adalah komik web, dan buku komik digital, termasuk terbitan tunggal dan publikasi perdagangan, dan konten digital lainnya termasuk animasi dan efek suara yang disediakan pada Layanan.</li>
                                <li class="mb-2"><b>"Website Komiktoon"</b> berarti www.komiktoon.com</li>
                                <li class="mb-2"><b>"Aplikasi Komiktoon"</b> berarti, secara kolektif, pembaca komik digital Komiktoon, aplikasi etalase, situs web dan/atau perangkat lunak (termasuk setiap pembaruan/peningkatan ke perangkat lunak tersebut) di mana Anda dapat membaca dan/atau menggunakan Konten Digital atau item lain yang ditawarkan oleh kami untuk digunakan pada satu atau lebih perangkat tertentu (misalnya, smartphone, tablet, PC/Mac, dkk.); dan mengelola Konten Digital dan pengaturan akun Anda.</li>
                                <li class="mb-2"><b>"Postingan Pengguna"</b> berarti konten, termasuk teks, data, foto, grafik, gambar, informasi, dan setiap kombinasi elemen ini yang Anda dan pengguna lain kirimkan ke Layanan, termasuk melalui komentar dan fitur lain seperti Profil Kreator.</li>
                            </ol>

                            <p class="fw-500">Lisensi Konten Digital dan Postingan Pengguna</p>
                            <ol type="A" class="text-gray fs-sm">
                                <li class="mb-2"><b>Kepemilikan Konten Digital.</b> Anda memahami dan menyetujui bahwa Layanan (termasuk Situs Komiktoon dan Aplikasi Komiktoon) dimiliki oleh Komiktoon. Konten Digital yang tersedia di Layanan dimiliki oleh Komiktoon atau dilisensikan oleh pemilik hak cipta yang berlaku untuk Komiktoon. Situs Web Komiktoon, Aplikasi Komiktoon, Konten Digital, perangkat lunak, antarmuka visual, elemen interaktif, fitur, informasi, grafik, desain, kompilasi, kode komputer, produk, tampilan dan nuansa, dan semua elemen Layanan lainnya, dilindungi oleh undang-undang dan perjanjian Amerika Serikat, Republik Korea, dan negara lain yang berkaitan dengan perlindungan kekayaan intelektual dan hak milik, termasuk undang-undang hak cipta, paten, tampilan dagang, dan merek, serta undang-undang yang berkaitan dengan perlindungan dan keamanan data. Komiktoon tidak mengalihkan kepemilikan, hak, atau kepentingan apa pun ke atau dalam Layanan dan/atau Konten Digital kepada Anda.</li>

                                <li class="mb-2"><b>Lisensi Konten Digital untuk Anda.</b> Setelah Anda mengunduh dan/atau menggunakan Konten Digital, Komiktoon memberi Anda lisensi terbatas, non-eksklusif, dan tidak dapat dialihkan, tidak dapat disublisensikan, dan dapat dicabut untuk mengakses, melihat, mengunduh (untuk waktu terbatas), dan menggunakan Konten Digital tersebut, semata-mata untuk penggunaan pribadi non-komersial Anda yang sesuai dengan ketentuan Perjanjian, selama Anda mengakses Konten Digital hanya di negara tempat Anda membuat akun dan/atau hanya di lokasi geografis tempat kami menawarkan Layanan kami dan memiliki lisensi Konten Digital tersebut. Ketersediaan Konten Digital dapat bervariasi berdasarkan lokasi geografis dan dapat berubah dari waktu ke waktu. Lisensi tidak memberi Anda kepentingan kepemilikan apa pun dalam Konten Digital tersebut. Dalam Situs Web Komiktoon dan Aplikasi Komiktoon, Anda dapat mengakses, melihat, atau menggunakan Konten Digital dan/atau dalam Aplikasi Komiktoon, Anda dapat mengunduh Konten Digital hanya ke satu perangkat yang akan dipertahankan hingga tiga puluh (30) hari dan Konten Digital tersebut dapat dihapus secara otomatis dari perangkat Anda setelah tiga puluh (30) hari. Konten Digital dilisensikan kepada Anda oleh Komiktoon; Konten Digital tidak dijual, dialihkan, atau diberikan kepada Anda.</li>

                                <li class="mb-2"><b>Pembatasan terhadap Lisensi Konten Digital.</b> Kecuali dinyatakan lain secara tertulis oleh Komiktoon, Anda tidak boleh menyalin, mendistribusikan ulang, mentransmisikan, menjual, menyewakan, menyewakan, menyampaikan, menyampaikan kembali, memposting, mempertunjukkan, menyiarkan, mengalihkan, menampilkan, atau mensublisensikan Konten Digital, atau menyediakan hak apa pun untuk Konten Digital, selain Postingan Pengguna Anda sendiri. Anda tidak boleh mengakali, memodifikasi, menghindari, memintas, menghapus, menonaktifkan, merusak, atau mengalahkan perangkat lunak manajemen hak digital, enkripsi, pensinyalan hak, atau teknologi perlindungan hak cipta yang digunakan untuk mengirim atau melindungi Konten Digital, atau di mana Konten Digital dibungkus atau terkait dengan (atau mencoba untuk melakukan salah satu hal di atas), dan Anda tidak boleh mengedit, memodifikasi, menerjemahkan, atau membuat karya turunan atau adaptasi dari Konten Digital, selain dari Postingan Pengguna Anda sendiri. Anda tidak boleh menggandakan atau mereproduksi (termasuk namun tidak terbatas pada "burning") Konten Digital (selain Postingan Pengguna Anda sendiri), atau bagian apa pun darinya, ke media fisik, memori, atau perangkat apa pun (selain di dalam perangkat pribadi Anda yang diizinkan) untuk mengunduh Konten Digital hingga jangka waktu yang ditentukan oleh Komiktoon), termasuk namun tidak terbatas pada CD, DVD, komputer atau perangkat keras lainnya, atau media lain apa pun yang sekarang dikenal atau selanjutnya dibuat. Anda tidak boleh menghapus atau mengubah merek dagang, merek jasa, atau logo apa pun atau hak cipta, merek, atau pemberitahuan kekayaan intelektual lainnya, atau pemberitahuan atau label hak milik lainnya pada atau di dalam Konten Digital. Anda tidak boleh menggunakan Konten Digital apa pun dengan cara yang melanggar hukum atau pelanggaran.</li>
                            </ol>

                            <p class="fw-500">Situs Website Komiktoon</p>
                            <ol type="A" class="text-gray fs-sm">
                                <li class="mb-2"><b>Penggunaan Situs Komiktoon dan Aplikasi Komiktoon.</b> Anda dapat menggunakan Layanan, termasuk perangkat lunak yang menyusunnya, hanya berdasarkan jumlah dan jenis (jika terbatas) perangkat yang kami izinkan untuk Anda unduh. Anda tidak boleh (i) memisahkan setiap komponen perangkat lunak tersebut untuk digunakan pada perangkat atau komputer lain; (ii) mentransfernya untuk digunakan pada perangkat atau komputer lain atau menggunakannya, atau sebagian darinya, melalui jaringan, atau (iii) menjual, menyewakan, mempersewakan, meminjamkan, mendistribusikan, atau mensublisensikan atau dengan cara lain mengalihkan hak apa pun atas perangkat lunak tersebut seluruhnya atau sebagian. Kami tidak dapat menjamin Layanan akan dengan benar atau langsung mencerminkan preferensi dan tindakan Anda secara keseluruhan atau sebagian.</li>

                                <li class="mb-2"><b>Pembuatan Akun.</b> Anda mungkin perlu mendaftar akun untuk mengakses beberapa atau semua Layanan. Anda bertanggung jawab untuk selalu memperbarui informasi akun Anda, mengambil langkah-langkah yang wajar untuk menjaga kerahasiaan nama pengguna dan kata sandi Anda, dan untuk semua aktivitas yang terjadi di bawah akun Anda. Anda setuju untuk segera memberi tahu kami tentang penggunaan yang tidak sah atas nama pengguna, kata sandi, atau informasi akun Anda lainnya, atau pelanggaran keamanan aktual atau yang dicurigai secara wajar yang Anda ketahui melibatkan akun Anda atau Layanan. Kami tidak akan bertanggung jawab kepada Anda atas kerugian yang mungkin Anda alami akibat orang lain menggunakan nama pengguna, kata sandi, atau akun Anda dengan atau tanpa sepengetahuan Anda. Anda dapat dimintai pertanggungjawaban atas kerugian yang dialami oleh Komiktoon atau pihak lain karena penggunaan nama pengguna, kata sandi, atau akun Anda secara tidak sah. Anda tidak boleh menggunakan akun orang lain kapan pun tanpa izin dari pemegang akun.</li>

                                <li class="mb-2"><b>Pembaruan.</b> Untuk menjaga agar Situs Web dan/atau Aplikasi Komiktoon tetap terkini dan sesuai, Komiktoon dapat menyediakan pembaruan/peningkatan ke Situs Web dan/atau Aplikasi Komiktoon. Jika Anda tidak mengunduh pembaruan/peningkatan tersebut, penggunaan Anda atas Layanan mungkin tidak aman, dan Anda mungkin tidak menerima fitur, fungsi, atau pemberitahuan tertentu dan/atau Anda dapat kehilangan akses ke fitur, fungsi, atau pemberitahuan tertentu dari Komiktoon Situs web dan/atau Aplikasi Komiktoon.</li>
                                
                                <li class="mb-2"><b>Tidak Ada Rekayasa Balik, Dekompilasi, Pembongkaran, atau Pengelakan.</b> Anda tidak boleh memodifikasi, merekayasa balik, mendekompilasi, mereproduksi, menyalin, membongkar Situs Komiktoon dan/atau Aplikasi Komiktoon atau komponen lain dari Layanan atau Konten Digital atau mengurangi Layanan atau perangkat lunak atau data apa pun di mana Konten Digital disimpan ke bentuk yang dapat dibaca manusia, baik seluruhnya atau sebagian, membuat karya turunan apa pun dari atau dari Situs Web Komiktoon, Aplikasi Komiktoon, atau komponen Layanan atau Konten Digital lainnya, atau memotong, memodifikasi, mengalahkan, atau mengutak-atik atau mengelakkan apa pun tentang fungsi atau perlindungan Website Komiktoon, Aplikasi Komiktoon, atau komponen Layanan atau Konten Digital lainnya; misalnya, dengan memodifikasi, mengalahkan, menambah, atau mengganti fungsi manajemen hak digital apa pun.</li>
                            </ol>

                            <p class="fw-500">Ketentuan Penggunaan</p>
                            <ol type="A" class="text-gray fs-sm">
                                <li class="mb-2"><b>Usia Minimal</b>
                                    <ol type="1">
                                        <li class="mb-2">Untuk menggunakan Layanan, Anda harus berusia minimal tiga belas (13) tahun (atau usia minimum yang diizinkan berdasarkan hukum yang berlaku di yurisdiksi Anda, jika lebih tinggi) ("Usia Minimum"). Penggunaan Layanan oleh siapa pun di bawah Usia Minimum tidak sah dan tidak berlisensi. Dengan menggunakan Layanan, Anda menyatakan dan menjamin bahwa Anda memenuhi persyaratan sebelumnya. Jika Anda tidak memenuhi persyaratan ini, Anda tidak dapat mengakses atau menggunakan Layanan.</li>
                                        <li class="mb-2">Jika Anda berusia antara 13 dan 18 tahun (atau antara Usia Minimum dan usia mayoritas yang sah di yurisdiksi tempat tinggal Anda, "Anak Di Bawah Umur"), Anda hanya dapat menggunakan Layanan di bawah pengawasan orang tua atau wali yang sah ( "Perwakilan") yang setuju untuk terikat dengan Perjanjian ini.</li>
                                        <li class="mb-2">Anda menyatakan kepada kami bahwa (i) Anda setidaknya berada pada Usia Minimum atau sebaliknya akan memberi kami informasi kontak orang tua atau wali Anda agar kami mendapatkan persetujuan yang sesuai dengan undang-undang yurisdiksi Anda dan (ii) jika Anda seorang Di bawah umur, Anda hanya dapat menggunakan Layanan di bawah persetujuan dan pengawasan Perwakilan yang setuju untuk terikat oleh Perjanjian, dan penggunaan Layanan adalah untuk tujuan pribadi. Kami dapat meminta Anda untuk memberikan bukti persetujuan Perwakilan Anda atau usia Anda. Kami juga dapat menghentikan penggunaan Anda atas Layanan jika kami mengetahui bahwa salah satu pernyataan Anda kepada kami tidak benar. Anda menyatakan bahwa jika Anda adalah Anak di Bawah Umur, Perwakilan Anda telah membaca dan menyetujui Ketentuan Penggunaan dan Kebijakan Privasi ini sebelum Anda mulai menggunakan Layanan atau produk atau layanan lain yang ditawarkan oleh Komiktoon. Kami menyarankan Perwakilan yang mengizinkan Anak di Bawah Umur yang diwakilinya untuk menggunakan Layanan untuk berkomunikasi dengan mereka tentang keamanan online, serta tentang rating konten dan konten yang terkadang tidak pantas yang mungkin ditemukan di Layanan. Anak di Bawah Umur yang Diwakili yang diizinkan untuk menggunakan layanan interaktif apa pun harus diberi tahu oleh Perwakilan mereka tentang potensi risiko bagi mereka. Perwakilan harus bertanggung jawab atas tindakan atau kelalaian Anak di Bawah Umur yang diwakilinya.</li>
                                    </ol>
                                </li>
                                <li class="mb-2"><b>Penggunaan yang Dapat Diterima.</b> Anda tidak boleh mengakses atau menggunakan, atau berupaya mengakses atau menggunakan, Layanan untuk mengambil tindakan apa pun yang dapat merugikan Komiktoon, afiliasinya, penyedia layanan, pemberi lisensi, atau pihak ketiga lainnya, mengganggu pengoperasian Layanan, atau menggunakan Layanan dengan cara yang melanggar hukum apa pun. Misalnya, dan tanpa batasan, Anda tidak boleh:
                                    <ol type="1">
                                        <li class="mb-2">erkedok sebagai orang atau entitas apa pun atau salah merepresentasikan afiliasi Anda atau asal materi yang Anda transmisikan;</li>
                                        <li class="mb-2">mengizinkan orang lain untuk menggunakan Layanan di bawah akun Anda;</li>
                                        <li class="mb-2">terlibat dalam "crawling", "scraping", atau p engambilan konten atau informasi pribadi yang tidak sah, atau menggunakan sarana otomatis tidak sah lainnya untuk mengumpulkan informasi yang tersedia melalui Layanan;</li>
                                        <li class="mb-2">mengambil tindakan apa pun yang menimbulkan beban besar yang tidak wajar atau tidak proporsional pada jaringan atau infrastruktur Komiktoon;</li>
                                        <li class="mb-2">menggunakan perangkat, perangkat lunak, atau rutinitas apa pun untuk mengganggu atau mencoba mengganggu kerja Layanan yang semestinya atau aktivitas apa pun yang dilakukan di Layanan atau mencoba menyelidiki, memindai, menguji kerentanan, atau melanggar keamanan sistem apa pun atau jaringan;</li>
                                        <li class="mb-2">mencoba untuk menguraikan, mendekompilasi, membongkar, atau merekayasa balik salah satu perangkat lunak yang terdiri dari atau dengan cara apa pun menjadi bagian dari Layanan;</li>
                                        <li class="mb-2">mendistribusikan materi yang tidak sah atau mengiklankan atau mempromosikan barang atau layanan melalui Layanan tanpa izin Komiktoon (termasuk, tanpa batasan, dengan mengirimkan spam); atau</li>
                                        <li class="mb-2">terlibat dalam perilaku lain apa pun yang membatasi atau menghalangi siapa pun untuk menggunakan atau menikmati Layanan, atau bahwa, menurut penilaian Komiktoon sendiri, memaparkan Komiktoon atau pengguna, afiliasi, atau pihak ketiga Komiktoon mana pun atas kewajiban, kerusakan, atau kerugian apa pun dari jenis apa pun.</li>
                                    </ol>
                                    Pelanggaran sistem atau keamanan jaringan dapat mengakibatkan pertanggungjawaban perdata atau pidana. Komiktoon dapat menyelidiki dan bekerja sama dengan otoritas penegak hukum untuk menuntut pengguna yang melanggar Perjanjian.
                                </li>

                                <li class="mb-2">Kepatuhan terhadap Hukum dan Reservasi Hak. Anda harus menggunakan Layanan dan Konten Digital sesuai dengan undang-undang yang berlaku dan Anda tidak boleh menggunakan Layanan dengan cara apa pun yang dapat berdampak merugikan pada Layanan, Komiktoon, penggunanya, atau pihak ketiga lainnya. Semua lisensi bersifat non-eksklusif dan semua hak yang tidak diberikan secara tegas dalam Perjanjian ini dicadangkan untuk Komiktoon.</li>

                                <li class="mb-2"><b>Moderasi Konten.</b> Anda mengakui dan menyetujui bahwa kami dapat menggunakan alat, personel, dan sistem otomatis dan/atau kebijaksanaan untuk meninjau, memantau, dan memoderasi Postingan Pengguna, Konten Digital, dan konten lain di Layanan untuk pelanggaran Perjanjian atau kebijakan dan pedoman yang ada dan yang akan datang, dan hukum yang berlaku. Kebijakan konten kami, beserta hukuman atas pelanggarannya, secara lebih khusus dijelaskan dalam <a href="/privacy-policy" class="text-primary text-decoration-none">Kebijakan Komunitas</a> dan Pedoman Pengunggahan kami.</li>
                            </ol>

                            <p class="fw-500">Privasi</p>
                            <ol type="A" class="text-gray fs-sm">
                                <li class="mb-2">Komiktoon menghormati privasi Anda dan telah menetapkan kebijakan dan prosedur tertentu yang berkaitan dengan pengumpulan dan penggunaan informasi pribadi Anda sehubungan dengan penggunaan Anda atas Layanan. Kebijakan Privasi kami tersedia di Situs Web Komiktoon dan/atau Aplikasi Komiktoon dan berlaku untuk penggunaan Anda atas Layanan. Harap baca Kebijakan Privasi kami untuk memahami cara kami mengumpulkan dan menggunakan informasi pribadi Anda.</li>
                                <li class="mb-2">Kami tidak dengan sengaja mengumpulkan informasi pribadi dari pengguna di bawah usia 13 tahun (atau usia minimum yang disyaratkan di yurisdiksi tempat tinggal Anda) tanpa persetujuan dari orang tua atau wali yang sah. Setiap orang tua atau wali yang meyakini bahwa pengguna di bawah usia 13 tahun (atau usia minimum yang disyaratkan di yurisdiksi tempat tinggal Anda) mungkin telah memberikan informasi pribadi tanpa persetujuan mereka harus menghubungi kami di Layanan Pelanggan. Dalam kasus tersebut, dalam penilaian wajar kami, kami dapat menghapus informasi pribadi pengguna tersebut di bawah usia 13 tahun (atau usia minimum yang dipersyaratkan di yurisdiksi tempat tinggal Anda).</li>
                                <li class="mb-2">Jika Anda mengakses layanan pihak ketiga, seperti Facebook, Google, atau Twitter, melalui Layanan untuk masuk ke Layanan atau berbagi informasi tentang pengalaman Anda di Layanan dengan orang lain, layanan pihak ketiga ini mungkin dapat mengumpulkan informasi tentang Anda, termasuk informasi tentang aktivitas Anda di Layanan, dan mereka dapat memberi tahu koneksi Anda di layanan pihak ketiga tentang penggunaan Layanan oleh Anda, sesuai dengan kebijakan privasi mereka sendiri.</li>
                                <li class="mb-2">Jika Anda memilih untuk terlibat dalam aktivitas publik di Layanan, Anda harus mengetahui bahwa setiap informasi yang Anda bagikan di sana dapat dibaca, dikumpulkan, atau digunakan oleh pengguna lain di area ini. Anda harus berhati-hati dalam mengungkapkan informasi pribadi saat berpartisipasi di area ini. Kami tidak bertanggung jawab atas informasi yang Anda pilih untuk disampaikan di area publik ini.</li>
                                <li class="mb-2">Komiktoon dapat berkomunikasi dengan Anda tentang Layanan, termasuk melalui satu atau lebih email pihak ketiga atau layanan survei, melalui metode yang ditentukan oleh Komiktoon, termasuk melalui Layanan atau informasi kontak yang Anda berikan sebagai bagian dari proses pendaftaran Layanan. Anda setuju untuk menerima komunikasi dari Komiktoon yang dapat: (i) meminta Masukan melalui email, survei, laporan bug, atau metode lain yang ditentukan oleh Komiktoon; (ii) mengumpulkan informasi tambahan terkait masalah yang Anda laporkan dalam Masukan Anda; (iii) memberi tahu Anda tentang perubahan pada Layanan atau Perjanjian; dan (iv) memberi tahu Anda tentang program, produk, atau layanan Komiktoon di masa mendatang.</li>
                            </ol>

                        </div>
                    </div>
                </div>  
            </div>
        </div>
    </div>

@endsection




